language: objective-c
 
branches:
 only:
 - master
 
xcode_project: PureMVC.xcodeproj
xcode_scheme: PureMVC
osx_image: xcode7.2 
 
script:
- xcodebuild clean build test -project PureMVC.xcodeproj -scheme PureMVC CODE_SIGN_IDENTITY=""
  CODE_SIGNING_REQUIRED=NO