language: objective-c
 
branches:
 only:
 - master
 
xcode_project: PureMVC.xcodeproj
xcode_scheme: PureMVC
osx_image: xcode7.2
xcode_sdk: iphonesimulator9.2 
 
script:
- xcodebuild [DEFAULT_OPTIONS] CODE_SIGNING_REQUIRED=NO